### ISSUE TITLE
源码使用问题

### ISSUE THREAD

**Issue by writinue** [NoThingNoDust/TrackDemo#3]
老哥，突然看到本项目中使用了https://gitee.com/huoyo/ko-time.git源码并作了修改，但是未注明出处，是否申明一下呢

**Comment by NoThingNoDust** [comment]
接受老哥批评，现在就去添加，感谢老哥指正。

**Comment by NoThingNoDust** [comment]
> 老哥，突然看到本项目中使用了[https://gitee.com/huoyo/ko-time.git源码并作了修改，但是未注明出处，是否申明一下呢](https://gitee.com/huoyo/ko-time.git%E6%BA%90%E7%A0%81%E5%B9%B6%E4%BD%9C%E4%BA%86%E4%BF%AE%E6%94%B9%EF%BC%8C%E4%BD%86%E6%98%AF%E6%9C%AA%E6%B3%A8%E6%98%8E%E5%87%BA%E5%A4%84%EF%BC%8C%E6%98%AF%E5%90%A6%E7%94%B3%E6%98%8E%E4%B8%80%E4%B8%8B%E5%91%A2)

已添加相关出处
